src/commands.js

This allows people to `greenkeeper init`, instead of `greenkeeper enable`, as discussed in semantic-release/cli#73

feat(alias): Add init alias for enable

---

src/commands.js

Hey :)
I was intuitively looking for a `status` command. So maybe aliasing it to `info` would be nice.
Best,
Finn

feat(alias): Alias status to info

---

src/login.js

Hi. I saw the same problem as #69. I'd like to see the URL even if I don't know the option `--verbose`.
```
$ greenkeeper login
oooo
`888
.ooooooooo  888  ooooo
8888' `8888  888 .88P'
8888   8888  8888888.       g r e e n k e e p e r . i o
`888bod88P'  888 `888b.
`Yooooooo. o888o o8888o
`Y88b
d88P   d888
`Y8888888P'
Login from this URL: https://api.greenkeeper.io/login?id=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```

show URL if fail to open

---

package.json
src/enable.js
src/login.js

Closes #46, requires https://github.com/greenkeeperio/website/pull/18.

feat(manual_webhooks): optionally removes need for admin scope

---

package.json
src/enable.js

This will check for the `branches.only` key in the `.travis.yml`. If it's present and there is no key matching the branchPrefix, it will show the following warning:
```
🌴  WARN enable Your .travis.yml is configured to only run for specific branches.
🌴  WARN enable For Greenkeeper to work you need to whitelist the Greenkeeper branches.
🌴  WARN enable Add this rule to branches.only in your .travis.yml:
🌴  WARN enable    - /^greenkeeper-.*$/
```
closes #222

feat: Show a warning if the .travis.yml excludes greenkeeper branches

---

package.json
src/info.js

This adds listing open PRs of a repository to the `gk info` command.
Example output (will be colored):
```
greenkeeper is enabled for this repository
Open pull requests:
- #251 npmlog@4.0.0 a month ago
- #246 inquirer@1.1.2 a month ago
Older pull requests might not be shown.
```

feat(info): Show list of open PRs, closes #150

---

LICENSE

Add an Apache 2 license file, so github is able to display the license in the top section of the project.

Add Apache 2 license file

---

package-lock.json
package.json

This a Greenkeeper PR that we lost while moving the repo.
We need to look into how the newly minified registry responses work with Greenkeeper before merging.

chore(package): update npm-registry-client to 8.3.0

---

jobs/github-event/push.js
lib/repository-docs.js
test/jobs/github-event/push.js
test/lib/repository-docs.js

Before we only synced the existing files on the initial branch. We need to make sure to sync the lock files on every push. This will result in a few more requests to GitHub, so we should check if we optimize this a bit more in the future.

fix: update repo doc files on every push

---

start-couchdb

Previously, when running `npm test`, the couchdb docker container sometimes took
longer than expected to be available to use, which lead to test
failures.
With this in place, we wait for the container to be available and then
start the test. This times out after 60 seconds of waiting.

chores: make start-couchdb wait for CouchDB being available

---

content/timeout-issue.js

Many people don't know how to go on after they activated CI on their repository because Greenkeeper does not activate automatically after that. So We added some instructions to get Greenkeeper enabled in that case.

feat(timeout-issue): improve wording on the no CI issue

---

jobs/registry-change.js
test/jobs/registry-change.js

so a (dev)dependency update will not accidentally update a peerDependency
or a pull request with the update will not be closed by Greenkeeper because
update is in the peerDependency range.

fix(registry-change): ignore peerDependencies

---

jobs/create-initial-pr-comment.js
jobs/github-event/pull_request/opened.js
jobs/github-event/status.js
test/jobs/create-initial-pr-comment.js
test/jobs/github-event/pull_request/opened.js
test/jobs/github-event/status.js

With this feature Greenkeeper can also be enabled when the user creates the initial pr (from the greenkeeper/inital branch)
Todo:

Feat: user created initial pr

---

.travis.yml

We've seen some issues with the lastest 5.3.0 and the
`node_modules/.bin` directory. Pinning to 5.2.0 solves this issue.
See https://github.com/npm/npm/issues/17882#issuecomment-317431382 for
some details.

fix(travis): pin npm to 5.2.0

---

test/jobs/create-initial-pr-comment.js

This test is a bit flaky from time to time. Increasing the wait time
should fix this, until we figure out why tap fires the afterEach too
early.

tests: higher timeout for waiting for tests

---

index.js
jobs/cancel-stripe-subscription.js
jobs/create-initial-pr.js
jobs/create-version-branch.js
jobs/github-event/marketplace_purchase/cancelled.js
jobs/github-event/marketplace_purchase/changed.js
jobs/github-event/marketplace_purchase/purchased.js
jobs/github-event/pull_request/closed.js
jobs/github-event/pull_request/opened.js
jobs/github-event/push.js
jobs/update-payments.js
lib/normalize-plan-name.js
lib/payments.js
package-lock.json
package.json
test/jobs/cancel-stripe-subscription.js
test/jobs/create-initial-pr.js
test/jobs/create-version-branch.js
test/jobs/github-event/marketplace_purchase/cancelled.js
test/jobs/github-event/marketplace_purchase/changed.js
test/jobs/github-event/marketplace_purchase/purchased.js
test/jobs/reset.js
test/jobs/update-payments.js
test/lib/payments.js
test/remove-if-exists.js

Background: with the Github Marketplace plans we can't do a 'pay as you go' model. We will have an 'opensource' plan (equals the 'free' plan), a 'team' plan which includes 15 private repos and a 'business' plan which includes unlimited everything.
so we need to:
-  [x] `pull_request/opened` (= user created  initial pr)
**Before we can deploy to prod:**

✨  Adapt to GitHub marketplace

---

index.js

If the queue is too big, the node process exceeds the 1GB limit. So stop using the fancy queue for now.

fix(Queue): work off the queue one by one

---

index.js

Revert hotfixes and re-add permanent solution.
Upped to 128 concurrent jobs because of observed queue-drain speed vs. ops resource usage.

Handle load spikes more gracefully

---

lib/github.js
package.json
test/jobs/github-event/installation/created.js
test/lib/github.js

I used Greenkeeper’s test suite to make sure there were no regressions and it helped greately. These are the changes to make it work with the new @octokit/rest package.
Greenkeeper used undocumented APIs before and is now using experimental APIs that will become public in future, so I pinned the version for now. I’m also thinking how to implement retry-logic more elegantly and as a generic plugin for everyone to use, maybe make it even a core plugin of `@rest/octokit` itself

github -> @octokit/rest

---

jobs/create-initial-branch.js
lib/env.js
test/jobs/create-initial-branch.js

This allows us to configure the host for our badges service. This fixes badge creation for staging (once we adapt the environment variable there and restart the service) and allows us to work in GKE environments.

chore(badges): make badge host configurable via environment

---

jobs/create-initial-branch.js
jobs/create-version-branch.js
lib/get-config.js
lib/get-message.js
lib/open-issue.js
package.json
test/lib/get-message.js

Add configuration options allowing Greenkeeper's commit message format to be customized as the user desires. These are handled exactly like other configuration options, as a `commitMessages` key in `package.json`. Some messages support data coming in, the format for this follows JavaScript's template literals.
This will allow Greenkeeper to fit in with any custom commit message format that a project requires, instead of forcing the conventional-commit style.
Within `package.json` the following keys are used as the default values:
```json
{
"greenkeeper": {
"commitMessages": {
"initialBadge": "docs(readme): add Greenkeeper badge",
"initialDependencies": "chore(package): update dependencies",
"initialBranches": "chore(travis): whitelist greenkeeper branches",
"dependencyUpdate": …
```

feat(config): add the ability to customize commit messages

---

lib/get-config.js
lib/get-message.js
test/lib/get-config.js

the Object.assign would overwrite the commitMessage object completely, causing problems when the user did not define **all** the necessary commit messages.

deep assign user config over default config

---

lib/get-release.js

This should fix the missing release notes. Problem was twofold:
- the `application/vnd.github.v3.html+json` header is required so the `body_html` field is returned, we bail if it isn’t
- the `accept` header key apparently became case sensitive at some point in the past, and we had always used `Accept`, which is now broken

fix: missing release notes

---

content/fail-issue.js
content/initial-pr.js
content/update-pr.js

Since there are a lot of users who we can’t contact by email, we show a note at the top of every PR or issue for the next six weeks that our Terms of Service have changed.  
Looks like this (but with April 6th instead of 5th)

feat: ToS notice on issues and prs

---

test/lib/get-diff-commits.js

The correct Content-Type header (as returned by GitHub’s API) is required as per https://github.com/octokit/rest.js/commit/02a40deac8a9de8eac61968175853144c091a513 (v15.1.0+)

Test: set content-type header in mock response

---

content/fail-issue.js
content/initial-pr.js
content/update-pr.js

The terms of service update notification has been at the top of all PRs and issues for a month now, for the remaining two weeks we’ll move it to the bottom so it‘s a bit less invasive.

feat: move tos update message to the bottom of issues and PRs

---

jobs/create-initial-branch.js
lib/get-files.js
lib/repository-docs.js
test/jobs/create-initial-branch.js

- it now saves the (complete) config to the repoDoc under the key 'greenkeeper'
- put the updating of an existing greenkeeper.json into a function
- had to get rid of the greenkeeperConfigInfo but added logs with infos
- updated updateRepoDoc so it always prioritises the filePaths from the auto discovery

fix(create-inital-branch): save generated greenkeeper config to the repoDoc

---

lib/validate-greenkeeper-json.js
test/jobs/create-version-branch.js
test/jobs/github-event/push.js
test/lib/validate-greenkeeper-json.js

We were preventing `@` and `-` in `package.json` paths in the config, and `-` in the group names. These chars are now allowed.

fix: validate package paths and groupnames more leniently

---

lib/validate-greenkeeper-json.js
test/lib/validate-greenkeeper-json.js

Adds a proper message when the greenkeeper.json isn’t actually JSON.

feat(validate-config-file): error message for malformed JSON

---

jobs/github-event/installation_repositories/added.js
test/jobs/github-event/installation_repositories/added.js

feat: retry 404 errors on `repos.get()`
adds logging so we can find out why we are getting a 404 here. If the case is that we are getting a notification about this before we actually do have access, we retry with the usual 5/3000 policy.
If we can’t get a repo info in five tries, we ignore the error and log the result.
feat: test new 404 retry behaviour and improve tests.
Test improvements:
- added test cases to raise coverage to 100%
- expect empty `pendingMocks` to ensure tests are written correctly
- use nock-local instance variables for tests
- make token requests optional, so tests can be run together and in isolation. The reason here is caching that we can not override from the test setup.

Fix: 404 on installation added

---

jobs/create-initial-branch.js
lib/default-commit-messages.js
test/jobs/create-initial-branch.js
test/lib/get-config.js

when editing the greenkeeper.json
**before**: it would edit but still commit it with "chore: add Greenkeeper config file"
**now**: it edits and commits with "chore: edit Greenkeeper config file"

fix(create-initial-branch): use appropriate commit message

---

test/jobs/registry-change.js
utils/utils.js

so we don't get the Rollbar Error:  `Error: can not identify job owner of create-group-version-branch`

fix: create-group-version-branch needs accountId

---

jobs/github-event/push.js
lib/diff-greenkeeper-json.js
lib/get-files.js
test/jobs/github-event/installation/created.js
test/jobs/github-event/push.js

~bit ugly 👼~
no longer ugly 😎 
fix(push): report malformed greenkeeper.json error on GitHub push
This one required a refactor of the GitHub push job, so it is a
little bit more involved.
Before, getGreenkeeperConfigFile was swallowing exceptions for
getting the file from GitHub and for parsing it.
Now, a parse error throws an error that in turn causes the
invalid-config-file job as per #678 and #672.
Also, GitHub errors now cause log entries, and return an empty
object, like the earlier default behaviour.

fix: report greenkeeper.json parse errors

---

test/jobs/github-event/installation/created.js
test/jobs/github-event/marketplace_purchase/purchased.js
test/jobs/github-event/push.js
test/lib/get-diff-commits.js
test/lib/get-files.js
test/lib/get-release.js
test/lib/handle-branch-status.js
test/lib/repository-docs.js
test/utils/initial-branch-utils.js

- test: make nock token-requests optional because of caching that we cannot override from test setup
- remove nock imports where we don't use it

Make nock token requests optional

---

jobs/create-initial-branch.js
lib/repository-docs.js
test/lib/repository-docs.js

This should fix #691 
The issue was that when the `greenkeeper.json` is invalid, we don’t return an empty object out of `get-files.js`, but an error. One level up, we then leave `greenkeeperConfigFile` undefined, which prevents everything else from happening.

fix(repo-docs): allow initial branch to continue with config file errors

---

lib/handle-branch-status.js
test/lib/handle-branch-status.js

for multiple group version branches + mention the group name (if there is one) in the pinning comment

fix(handle-branch-status): don't comment multiple times

---

lib/get-config.js
package.json
test/jobs/create-version-branch.js
test/lib/get-config.js

There was a small bug where an empty object in the `greenkeeper` key would prevent config data from the `package.json` config (`packages -> package.json -> greenkeeper -> stuff`) being fetched. See the two new tests for details.
First encountered [here](https://github.com/treasure-data/td-js-sdk/pull/105).

fix: merge repoDoc configs correctly

---

content/fail-issue.js
content/update-pr.js

wrap the name in `<code>` to avoid GitHub Markdown rendering bug
closes #635

fix(pr): show dependency name for scoped packages

---

jobs/deprecate-nodejs-version.js
test/jobs/deprecate-nodejs-version.js

Deprecate job crashed if the `package.json` was missing the engines key

fix(deprecate-node): handle missing engines key in package.json

---

jobs/deprecate-nodejs-version.js
test/jobs/deprecate-nodejs-version.js
test/utils/utils.js
utils/utils.js

- The regex didn’t handle things like `4.1.2` due to the extra `$` at the end
- `hasNodeVersion()` previously included wildcard strings like `stable` and `node` which always refer to the latest release, but we don’t always want that, so that’s a flag now. That also needed to propagate through `getNodeVersionIndex()`, which calls `hasNodeVersion()`

fix(deprecate-node): identify correct node versions in deprecation

---

.travis.yml
Dockerfile
package.json

Todo:
* * *
not used by enterprise, but we should get them all updated
Test procedure:

feat: test on node 8

---

jobs/monorepo-supervisor.js

for incomplete monorepo releases

feat(monorepo-supervisor): deactivate slacknotification 

---

lib/validate-greenkeeper-json.js
test/lib/validate-greenkeeper-json.js

They're valid characters in a directory name.
The single test passes, unfortunately I'm not able to run your test suite so I cannot validate whether all tests pass. While this is as it is we can't use you guys :(

fix: permit periods in package paths

---

lib/validate-greenkeeper-json.js
test/lib/validate-greenkeeper-json.js

Small extension to #791 , adds the newly allowed period in package paths to the text in the issues for invalid `greenkeeper.json` files.

fix(validate-greenkeeper-json): add period to allowed chars in issue txt

---

jobs/create-group-version-branch.js
jobs/create-version-branch.js
test/jobs/create-group-version-branch.js
test/jobs/create-version-branch.js

This adds a request to github in `create-version-branch` to check if the pull request is actually still open. It updates the database if there is an inconsistency.
I also adapted this for `create-group-version-branch`.
Should fix #752

 Do not comment on closed PR

---

utils/monorepo-definitions.js

As mentioned in [this doc](https://greenkeeper.io/docs.html#monorepo-dependencies) greenkeeper groups updates for projects that use monorepo approach for developing.
Tool I develop now is using Lerna in fixed mode, so it seems that it should be in this list in order to provide best experience for developers that use [BaseT](https://github.com/Igmat/baset) and [greenkeeper](https://greenkeeper.io/) together in their projects.
P.S.
Thanks for you great project - it helps a lot:)

Adding BaseT package to monorepo-definitions

---

jobs/create-group-version-branch.js
jobs/create-version-branch.js

We weren’t using `getMessage()` in two places, this is now fixed.
Closes #794

fix: add missing custom commit messages

---

test/jobs/registry-change.js
utils/utils.js

Fix:
- If there were multiple instances of the same single non-root `package.json` file in the updates for a monorepo, it wasn’t recognised as a monorepo.
That was this error: https://rollbar.com/neighbourhoodie/gk-jobs/items/6726/

fix(registry-change): always run group job if only one non-root pkg.json

---

content/fail-issue.js
content/update-pr.js
lib/handle-branch-status.js
lib/monorepo.js
lib/open-issue.js
package.json
test/jobs/create-group-version-branch.js
test/jobs/create-version-branch.js
test/jobs/registry-change.js
test/lib/monorepo.js

- uses the new external [greenkeeper-monorepo-definitions module](https://www.npmjs.com/package/greenkeeper-monorepo-definitions)
- adds more monorepo-related information to PRs and issues

External monorepo definitions and better monorepo wording

---

test/jobs/cancel-stripe-subscription.js
test/jobs/create-initial-pr.js
test/jobs/create-version-branch.js
test/jobs/github-event/installation/created.js
test/jobs/github-event/issues/closed.js
test/jobs/github-event/marketplace_purchase/cancelled.js
test/jobs/github-event/marketplace_purchase/purchased.js
test/jobs/github-event/pull_request/closed.js
test/jobs/github-event/pull_request/opened.js
test/jobs/github-event/push.js
test/jobs/github-event/status.js
test/jobs/initial-timeout-pr.js
test/jobs/invalid-config-file.js
test/jobs/stripe-event.js

We want a better overview of our setup and therefore place all the test setup (the Jest globals `beforeEach()`, `beforeAll()`, `afterEach()` and `afterAll()`) together in one place on top of each testfile.

refactor(test): move afterEach() to top of test file

---

jobs/create-group-version-branch.js
jobs/create-version-branch.js
jobs/registry-change.js
test/jobs/create-group-version-branch.js
test/jobs/create-version-branch.js
test/jobs/registry-change.js

Problem: people occasionally release prereleases with the `latest` distTag by accident. Nobody wants those releases, so we bail on them now.
- fix: Ignore releases on `latest` that have prerelease identifiers

fix: ignore prereleases with latest tag

---

jobs/github-event/repository/archived.js
test/jobs/github-event/repository/archived.js

Cherry-picked from #842 : 
- Disables repos when they’re archived. Does not re-enable repos when they’re unarchived, this still requires a reset.

feat(github-events): disable repos when they’re archived

---

content/initial-pr.js

instead of refering to `origin` using the https url (clone_url) provided by github
closes #350

use more general git instructions in initial PR instructions

---

jobs/create-version-branch.js
lib/monorepo.js
test/jobs/create-version-branch.js
test/lib/monorepo.js

We originally didn’t intend for group configurations to be used in non-monorepos, but there’s no reason to not respect ignore rules that come from there, as is the case in #852 
Changes:
- `create-version-branch` bails when a dependency is ignored in a group config that includes the  root `package.json`

fix(create-version-branch): use group ignore even if not a monorepo

---

jobs/create-initial-pr.js
jobs/create-initial-subgroup-pr.js
lib/default-pr-titles.js
test/lib/get-config.js
test/lib/get-message.js

Example greenkeeper config object in package.json:
```js
"greenkeeper": {
"commitMessages": {
"initialBadge": "Docs: Add Greenkeeper badge",
"initialDependencies": "Upgrade: Update dependencies",
"initialBranches": "Build: Whitelist greenkeeper branches",
"dependencyUpdate": ":gem: Upgrade: Update ${dependency} to version ${version}",
"devDependencyUpdate": ":gem: Upgrade: Update ${dependency} to version ${version}",
"dependencyPin": "Fix: Pin ${dependency} to ${oldVersion}",
"devDependencyPin": "Fix: Pin ${dependency} to ${oldVersion}"
},
"prTitles": {
"initialPR": "Update dependencies to enable Greenkeeper!!!",
"initialPrBadge": "Add badge to enable Greenkeeper!!!!",
"initialPrBadgeOnly": "Add Greenkeeper badge!!!",
"initialSubgroupPR": "Update dependencies for ${group}!!!",
"basicPR": …
```

feat: add customisable initial PR titles

---

index.js
jobs/monorepo-supervisor.js
test/jobs/monorepo-supervisor.js
test/lib/worker.js

- add logs to monorepo-supervisor job
- reformates the scheduled job object to be wrapped in an object with a content key
- this way the scheduled job can return new jobs!

Fix: scheduling of jobs

---

jobs/create-group-version-branch.js
jobs/create-version-branch.js
test/jobs/create-group-version-branch.js
test/jobs/create-version-branch.js

because they can be different
it looks up the 'latest' distTag in our npm database for each dependency and sets that as a version. 
maybe it is better to ignore any dependencies that don't match the version that the release is for? 
-> so if the create-version-branch is called with version 2.0.0 and one of the monorepo dependencies is on 1.5.0 then it will not be included in the branch/PR

Fix: get latest version for each monorepo release dependency

---

lib/monorepo.js

upsert’s implementation produces an infinite lopp, if you pass
`_deleted: true`. We don’t want that.

fix: don’t use upsert to delete documents.

---

lib/create-branch.js
test/lib/__snapshots__/create-branch.js.snap
test/lib/create-branch.js

When generating lockfiles, do one per file, not one per commit per file.
Found by @hulkoba , closes #897

fix(create-branch): iterate over package files, not commits

---

jobs/create-group-version-branch.js
jobs/create-version-branch.js
jobs/registry-change.js
utils/utils.js

CVB amd CGVB did not prefix the installation ID when trying to access a private package in our npm releases db.

fix(private-packages): handle releases from webhook correctly

---

lib/create-branch.js

Less spam spam spam spam spam.

chore(create-branch): don’t log the entire lockfile on error

---

lib/github-queue.js

This allows us to graph the amount of GitHub requests by user,
or by GitHub method (i.e. API endpoint), or both.

feat: tag github request metrics by installationId and method

---

lib/lockfile.js
package.json
start-couchdb
test/lib/lockfile.js

A list of active exec servers is kept in CouchDB. For each exec
server request, we get that list.
Each job increments an active jobs counter, this allows us to
determine te server with the fewest jobs to send a new one to.
On network errors, we now try again with another server. Retries
are implemented with recursive function calls, and capped at 4
retries.
500 errors are not handled specially any more, as the exec server
mostly hides them now.

feat: support multiple exec servers

---

jobs/github-event/check_run/completed.js
jobs/github-event/check_suite/completed.js
lib/on-branch-status.js

Bit of a mixup with what comes from where, also handle the case that the payload may or may not include the `installation` object, but there’s no reasoning as to when or why that happens.

fix(github): handle event payloads properly

---

jobs/github-event/check_run/completed.js
lib/on-branch-status.js

If all checkruns are a success or neutral, set combinedState to `success`, else `failure`. This casts all failure conclusions (`cancelled`, `timed_out`, `action_required`, `failure`) as `failure`. Before, we ignored the first three, which led to some initial PRs not being created.

fix: handle all branch state conclusions properly

---

lib/on-branch-status.js
test/jobs/github-event/check_suite/completed.js
test/jobs/github-event/status.js

Since `getCombinedStatusForRef` doesn’t tell us how many statuses we should be waiting for, we now use `List statuses for a specific ref` instead.

fix: get all individual statuses on branch status

---

lib/on-branch-status.js
test/jobs/github-event/check_suite/completed.js
test/jobs/github-event/status.js

Get combined statuses for ref instead of just statuses, since the latter ignores the statuses context and delivers multiple statuses per… thing. Test run, for example.

fix(on-status): use combined status

---

jobs/github-event/installation/created.js

Fetching repositories from installations no longer worked after updating Octokit, partially because the [endpoint](https://octokit.github.io/rest.js/#api-Apps-listRepos) apparently didn’t include the accept header (at least we got `415`s back from GH), and partially because the pagination didn’t flatten the results per page down to one array as suggested in the docs. This fixes both.

fix: work around octokit inconsistencies

---

lib/get-files.js
lib/repository-docs.js
test/lib/get-files.js

Requesting a too large package-lock.json causes this:
```
{
"message": "This API returns blobs up to 1 MB in size. The requested blob is too large to fetch via the API, but you can use the Git Data API to request blobs up to 100 MB in size.",
"errors": [
{
"resource": "Blob",
"field": "data",
"code": "too_large"
}
],
"documentation_url": "https://developer.github.com/v3/repos/contents/#get-contents"
}
```
The gitHub API supports files up to 1 megabyte in size, so we need to use the Git Trees API for larger ones (and blob for the contents)

fix(lockfiles): handle too large lockfiles

---

jobs/create-group-version-branch.js
jobs/create-initial-pr.js
jobs/create-initial-subgroup-pr.js
jobs/create-version-branch.js

`github.pullRequests.getAll` is deprecated and `octokit.pulls.list()` works exactly the same way that `octokit.pullRequests.getAll()` worked before

fix(initial-pr): replace deprecated octokit getAllPrs-method

---

jobs/create-group-version-branch.js
jobs/create-version-branch.js
test/jobs/__snapshots__/create-group-version-branch.js.snap
test/jobs/__snapshots__/create-version-branch.js.snap
test/jobs/create-group-version-branch.js
test/jobs/create-version-branch.js

- changes the comments in the pr database doc from `2.0.9` to `@gatsby/cli-2.0.9`
- we can check if there is anything new in the branch or if we have one like this before
TODO:

Fix: only comment on PR if there are new updates
