src/lib/story.js
Add whitespace before username
=> fix(whitespace): typo

package.json, src/disable.js, src/enable.js
:rocket:
One of your dependencies has just updated, so this PR bumps the corresponding version number in your `package.json`.
You can now check that the dependency update doesn't break your code, and then release the new version of your software safe in the knowledge that it will stay in this working state, regardless of _when_ your users do `$ npm install`.
Have a good day!
---
This pull request was created by [greenkeeper.io](http://greenkeeper.io/).
It keeps your software, up to date, all the time.
<sub>
Tired of seeing this sponsor message? Upgrade to the supporter plan!
You'll also get your pull requests faster :zap:
</sub>
=> Updated github-slug to version 1.0.0

src/enable.js
=> fix(enable): use slug if passed via cli

src/lib/story.js
That's basically it. Couldn't push to master because it's protected :) (probably a good idea :D)
=> Feat(help): added reference to FAQ page

src/organization-access.js
=> fix(organization-access): handle enterprise API endpoints

src/lib/check-enterprise.js, src/upgrade.js
=> feat(upgrade): check if endpoint is greenkeeper enterprise API

README.md, package.json, src/commands.js, src/config.js, src/index.js, src/lib/rc.js
Can be used to persist API, loglevel etc.
Closes #109
=> Config Command

README.md, src/enable.js, src/lib/sync.js, src/login.js, src/sync.js
As suggested #113 this PR adds this feature. The output might still be a bit verbose and not perfect, but it seems to work. Would be good to get feedback on this.
=> Enable: Does a sync when the repo is not found

src/lib/check-enterprise.js, src/login.js
This will run `--private` automatically on `gk login` for enterprise instances. This closes #167
=> feat(login): include private repositories for enterprise instances

README.md, package.json
=> Use https in package.json and update link in README.md

.travis.yml, package.json, src/index.js, test/readme.js, test/smoke.js
2.11.0 broken due to https://github.com/npm/npm/issues/12542
=> Fix ENOENT README missing

package.json, src/index.js
=> fix: stop truncating output on newer node versions

package.json, src/login.js
=> Fix flags prio/ set api after login

package.json, src/commands.js, src/index.js, src/web-app.js
`gk web-app` opens it up in the browser.
A new banner will advertise this command on any other command, a maximum of 10 times though.
Running `gk web-app` once will make the banner go away.
@janl @christophwitzko @finnp
=> Add a banner to advertise web app and a command to open it

src/index.js
https://github.com/integration/greenkeeper
=> feat: add a banner that points to the new github integration

content/initial-pr.js, jobs/create-initial-branch.js, jobs/create-initial-pr.js, lib/repository-docs.js, test/jobs/create-initial-branch.js, test/lib/repository-docs.js
Sync the presence handled by `greenkeeper-lockfile` as a `files` key to database.
If a lock file exists show a message in the initial PR
=> feat: link to greenkeeper-lockfile if lockfile is present

content/update-pr.js, jobs/github-event/integration_installation/created.js, lib/payments.js
On May 31st the Greenkeeper 2 beta is ending. This pull request introduces the necessary changes to disable the beta plan. 🌴
=> Disable beta plan

lib/worker.js
This should fix the rollbar API problems.
=> fix(rollbar): report correctly

jobs/registry-change.js, test/jobs/registry-change.js
_based on https://github.com/greenkeeperio/greenkeeper/pull/465_
=> Handle duplicated dependencies

index.js
closes https://github.com/greenkeeperio/greenkeeper/issues/477
=> Fix reminder job

couchdb/repositories/_design/by_full_name/views/by_full_name/map.js, index.js, jobs/reset.js, test/jobs/reset.js
This job resets greenkeeper for a repository and creates a new initial branch.
So instead of telling the user to delete all greenkeeper branches and uninstalling and re installing the app, we can remotely enqueue this job and do it for them.
There will be an additional PR in the hooks repository.
=> ✨ 🔁  Reset job

jobs/schedule-stale-initial-pr-reminders.js
=> fix(stale-pr-reminders): correct path to db library

.github/ISSUE_TEMPLATE.md, README.md
=> feat: add coordinated disclosure info

content/timeout-issue.js
=> typo in "could not be activated" issue

lib/env.js
No biggie, just preparation :)
=> chore(env): add env var for GitHub enterprise

content/timeout-issue.js, lib/env.js, test/content/timeout-issue.js
This is a first step into us being a bit more independent of the GitHub host.
=> feat(timeout-issue): link to custom GitHub host if user has set the environment variable

content/fail-issue.js, content/initial-pr.js, content/payment-activated.js, content/timeout-issue.js, content/update-pr.js
Went through all the public-facing copy text Greenkeeper emits in PRs and issues, and revised it a bit. Made the bot less personal (`Greenkeeper will` instead of `I’ll`), and generally smoothed things out a bit.
=> refactor: revise wording in all PRs and issues

jobs/cancel-stripe-subscription.js, jobs/update-payments.js, test/jobs/update-payments.js
Three fixes Gregor mentioned in his review 👍
=> Gregor’s fixes for Adapt to GitHub marketplace

jobs/github-event/integration_installation/created.js, jobs/github-event/integration_installation/deleted.js, jobs/github-event/integration_installation_repositories/added.js, jobs/github-event/integration_installation_repositories/removed.js, package-lock.json, package.json
These either have no repositories as it is an account event or they have an array of repositories. So non of these logs have a repoSlug
=> Logging for installation events

lib/worker.js, test/lib/worker.js
As we don't have a repoSlug for most of these jobs, this will only work with https://github.com/greenkeeperio/gk-log/pull/4  so the repoSlug is considered optional in the initialization of the logs.
=> feat(worker): add logging

README.md, content/timeout-issue.js, jobs/github-event/installation/created.js, jobs/github-event/installation/deleted.js, jobs/github-event/installation_repositories/added.js, jobs/github-event/installation_repositories/removed.js, jobs/github-event/integration_installation/created.js, lib/get-token.js, test/jobs/github-event/installation/created.js, test/jobs/github-event/installation/deleted.js, test/jobs/github-event/installation_repositories/added.js, test/jobs/github-event/installation_repositories/removed.js
closes https://github.com/greenkeeperio/greenkeeper/issues/440
=> Update to breaking GitHub hooks changes

content/stripe-cancel-survey.js, jobs/send-stripe-cancel-survey.js, jobs/stripe-event.js, lib/env.js, package.json, test/jobs/send-stripe-cancel-survey.js, test/jobs/stripe-event.js
~Before merge: add new env variables to config!~ (done)
=> Send email when subsription is cancled

CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md
I took many sections from the awesome [semantic-release](https://github.com/semantic-release/semantic-release) Contributing Guide 💜 and the README.md header is heavily inspired by the one from [choojs](https://github.com/choojs/choo) 🚂 ✨.
=> Add CoC & Contributing Guide

content/stale-initial-pr-reminder.js
Yup, it’s really just a typo. Somebody accidentally a word out :)
=> fix: typo in stale pr reminder, fixes #585

test/jobs/create-version-branch.js
because if we use the same installation ids then the githubqueue
allready exists and won't need to make some of these requests!
=> test: add optional nock calls

jobs/github-event/pull_request/closed.js, jobs/github-event/push.js
Also helps with GKE, as this gives us a single point to change when we need to adapt :)
=> refactor: use maybeUpdatePaymentsJob instead of duplication

jobs/github-event/pull_request/opened.js
This is in the same vein as #596 and will make it easier for GKE later on.
=> refactor: don't check for payment when PR is opened and repo is public

jobs/create-initial-pr.js
Stumbled over this while checking for code adjustments for GKE: We don't need to check for payments if the repo is public anyway. Saves some requests to the database as well :)
(I'd love to refactor this into separate functions one day, but for now this should do)
=> refactor(initialPR): Don't check for payment on public repos

jobs/create-version-branch.js
Also removes some unused arguments from the `prContent` call
=> refactor(create-version-branch): don't check for payment on public repos

package.json
=> fix(package): update jsonwebtoken to version 8.1.1

package.json
=> fix(package): update @octokit/rest to version 14.0.5

README.md
The readme was missing the new logo 🖌
=> docs(readme): update banner

CONTRIBUTING.md, test/readme.md
Add basic test documentation 
Link docu on contributing.md
=> Test documentation

README.md
Fixes the not working redirect to the dev dependencies sub page.
=> README.md fixes not working URL

package.json
=> fix(package): update @octokit/rest to version 14.0.9

jobs/create-initial-branch.js, lib/default-commit-messages.js, lib/get-files.js, lib/repository-docs.js, test/jobs/create-initial-branch.js, test/lib/get-config.js, test/lib/get-files.js
=> Fix Monorepo Feature

jobs/create-initial-branch.js, test/jobs/create-initial-branch.js
Wasn’t actually happening yet :D
=> fix(create-initial-branch): iterate over all package.jsons

content/initial-pr.js, jobs/create-initial-branch.js, jobs/create-initial-subgroup-branch.js, test/jobs/create-initial-branch.js
=> fix(create-initial-pr): detect dependency updates for messages #677

test/jobs/create-initial-subgroup-branch.js, test/utils/initial-branch-utils.js, utils/initial-branch-utils.js
=> Fix create initial subgroup branch missing package.json

jobs/create-group-version-branch.js, jobs/create-initial-branch.js, jobs/github-event/push.js, lib/repository-docs.js
Closes #690 and almost but not quite does the same for #676
=> Fix/use config string for closing commit msg + better logs

jobs/create-initial-branch.js, lib/invalid-config-file.js
=> fix: normalise inconsistent key case, camel vs snake

content/initial-pr.js, jobs/github-event/status.js, lib/invalid-config-file.js, test/jobs/github-event/push.js
Issue number didn't make it into the PR, this is now fixed.
=> fix: fetch issue numbers of closable issues properly

content/fail-issue.js, jobs/create-group-version-branch.js, jobs/create-version-branch.js, lib/handle-branch-status.js, lib/open-issue.js, test/lib/handle-branch-status.js, test/lib/open-issue.js, test/utils/utils.js, utils/utils.js
Also refactor url generation into a separate utils function
Fixes #682
=> fix: generate correct github compare urls

jobs/send-stripe-cancel-survey.js, lib/env.js
=> fix: use mandrill for sending emails

jobs/update-nodejs-version.js, test/jobs/update-nodejs-version.js
Don’t run a specific node update for a repo if it already has a branchDoc for that update.
Re-uses the `dependency` and `dependencyType` keys so we don‘t need new views:
```js
dependency: 'node-10',
dependencyType: 'node-update'
```
This way we can differentiate between versions, and updates and deprecations.
=> fix(node-update): bail if there’s already a branch for this node update

jobs/github-event/status.js, jobs/update-nodejs-version.js
So it can be found by the `issue_open_by_dependency` view. If it can’t the corresponding branch gets deleted.
=> fix(node-update): pass dependency to update issue

jobs/create-initial-branch.js, test/jobs/create-initial-branch.js
=> fix(initial-branch): get updated config from repodoc before ignoring

lib/github-queue.js
this will be a bit spammy in the logs, but will help us fix a bunch of issues down the road
=> feat: log all github exceptions

jobs/github-event/installation_repositories/added.js, lib/dbs.js, test/jobs/github-event/installation_repositories/added.js
This reverts commit 21aaaed305571179a97c50326ada86625ac163eb.
=> Revert "fix: minimize retries for now"

content/nodejs-deprecate-issue.js, jobs/deprecate-nodejs-version.js, test/jobs/deprecate-nodejs-version.js
Allows passing in an optional annoucement URL to the nodejs deprecation issue job.
=> feat(node-deprecation): add optional announcementURL to issue

test/readme.md
BREAKING CHANGE: hopefully none, but just in case, all the monorepo
work warrants a new major version. Go team!
=> feat: add newline to readme to start release procedure :)

jest.setup.js, package.json, test/jobs/create-group-version-branch.js, test/jobs/create-initial-branch.js, test/jobs/create-initial-pr.js, test/jobs/create-initial-subgroup-branch.js, test/jobs/create-initial-subgroup-pr.js, test/jobs/create-version-branch.js, test/jobs/deprecate-nodejs-version.js, test/jobs/github-event/installation/created.js, test/jobs/github-event/installation/deleted.js, test/jobs/github-event/marketplace_purchase/changed.js, test/jobs/github-event/marketplace_purchase/purchased.js, test/jobs/github-event/push.js, test/jobs/github-event/status.js, test/jobs/registry-change.js, test/jobs/send-stripe-cancel-survey.js, test/jobs/update-nodejs-version.js, test/lib/monorepo.js, test/lib/open-issue.js
=> test: put jest timeout in setupfile

jobs/create-group-version-branch.js, test/jobs/create-group-version-branch.js
of monorepo-group in one package.json
=> fix(create-group-version-branch): update deps and devDeps 

index.js
=> fix(index): block spammer tectronics by id as well (13286164)

README.md
=> feat(deploy): deploy commit

lib/enterprise-setup.js, test/lib/enterprise-setup.js
=> feat(gke-setup): add and remove logsDB automatically

jobs/create-version-branch.js
=> feat(create-version-branch): remove unused message-creation code

jobs/create-group-version-branch.js, jobs/create-initial-branch.js, jobs/create-initial-subgroup-branch.js, jobs/create-version-branch.js, jobs/github-event/push.js, test/jobs/create-group-version-branch.js, test/jobs/create-initial-branch.js, test/jobs/create-initial-subgroup-branch.js, test/jobs/create-version-branch.js, test/jobs/github-event/push.js, utils/utils.js
and enable temporary disabled repository again (see #789)
=> feat: limit allowed package.jsons per repo (max 300)

content/fail-issue.js, content/update-pr.js, lib/get-infos.js, test/lib/get-infos.js
=> fix(content): use html-dependency-link

lib/dbs.js
Lowers resource use on first run
=> fix(dbs): limit bootstrap concurrency

jobs/create-group-version-branch.js, jobs/create-version-branch.js, jobs/registry-change.js, test/jobs/create-group-version-branch.js, test/jobs/create-version-branch.js, test/jobs/registry-change.js, test/utils/utils.js, utils/utils.js
re-allow prereleases for latest for people who use prereleases before
=> feat: allow prereleases for user using it before

jobs/monorepo-supervisor.js
=> fix(monorepo-supervisor): releases are not arrays of promises!

README.md
=> fix: highlight something in the readme so we get a new npm version

jobs/monorepo-supervisor.js, test/jobs/monorepo-supervisor.js
and not undefined
this should hopefully fix the monorepo releases now!
=> fix(monorepo-supervisor): send data from the database doc

lib/create-branch.js, test/lib/__snapshots__/create-branch.js.snap
using toString instead of json stringify
=> fix(create-branch): convert lockfile contents to string

content/fail-issue.js, lib/open-issue.js, test/content/__snapshots__/fail-issue.js.snap, test/content/fail-issue.js
`packageUpdateList` was not handed down to `open-issue.js`
=> fix(content/fail-issue): hand down the list of package updates

lib/get-infos.js
=> feat: cache getInfo calls in memory

jobs/registry-change.js, test/jobs/registry-change.js, utils/registry-change-utils.js
Asana ticket: https://app.asana.com/0/285414386571203/844311934712717
=> send multiple, smaller allDocs requests

content/timeout-issue.js
now our customers should use the reset button.
=> docs(issue): change reset instructions.

content/initial-pr.js, test/jobs/__snapshots__/create-initial-pr.js.snap
Our info text about this in the initial PR wasn’t particularly great, this should help.
=> fix(pr): update info about private scoped packages

package.json
=> fix(package): update @octokit/rest to version 15.17.0

content/invalid-config-issue.js
=> fix(invalid config issue): have valid json as an example of a valid json

lib/create-branch.js
=> fix(lockfile): only write to token-audits if there are tokens... 

jobs/reset.js
and add a more descriptive log
=> fix(reset): use given accountId to create tmp doc

jobs/github-event/installation/created.js, lib/get-token.js, lib/github-queue.js, lib/github.js, package.json, test/lib/get-token.js
Closes #1022
see [https://github.com/octokit/rest.js#client-options](https://github.com/octokit/rest.js#client-options)
=> fix(package): update @octokit/rest to version 16.14.0

content/payment-required.js, jobs/create-initial-branch.js, jobs/github-event/installation_repositories/removed.js, jobs/github-event/pull_request/closed.js, jobs/github-event/push.js, jobs/github-event/repository/archived.js, jobs/github-event/repository/privatized.js, jobs/payment-required.js, jobs/update-payments.js, lib/payments.js, lib/repository-docs.js, test/jobs/github-event/repository/privatized.js, test/jobs/invalid-config-file.js, test/jobs/payment-required.js, test/lib/payments.js
:warning:  somebody else (@espy ?) should formulate the issue-text
=> Handle free private repos

package.json
=> fix(package): update @octokit/rest to version 16.19.0

lib/create-branch.js
for error on lockfile creation
=> fix(createBranch): change logging types

jobs/create-group-version-branch.js, jobs/create-version-branch.js
I adapted the log message from warn to info and added more context to the text to make it not seem like an error
=> fix(create-*-version-branch): more informative log message

lib/worker.js
when it does not have a message
=> fix(worker): send whole error to rollbar

content/update-pr.js, test/jobs/__snapshots__/create-version-branch.js.snap
=> fix(pr content): make license change more eye catching
